# Generated by Django 3.0.5 on 2020-07-26 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dev', '0003_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['created_on']},
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='created_date',
            new_name='created_on',
        ),
    ]
