# Generated by Django 3.0.8 on 2020-08-04 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dev', '0007_comment_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='image',
            field=models.ImageField(default='static/dev/profiler.png', upload_to=''),
        ),
    ]
