# Generated by Django 3.0.8 on 2020-08-04 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dev', '0009_auto_20200804_0755'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='image',
            field=models.ImageField(default='dev/images/default.jpg', upload_to='dev/images/'),
        ),
    ]
