# Generated by Django 3.0.5 on 2020-07-26 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tech', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='techpost',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
